/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static oracle.sql.NUMBER.e;

/**
 *
 * @author usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    conexiones con = new conexiones();

    /**
     * Creates new form Ventana
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        con.conectar();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenu();
        jMenuItemCiudad = new javax.swing.JMenuItem();
        jMenuItemEquipos = new javax.swing.JMenuItem();
        jMenuItemPartidos = new javax.swing.JMenuItem();
        jMenuItemMarcador = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu_ver = new javax.swing.JMenu();
        jMenuItemTablaPos = new javax.swing.JMenuItem();
        jMenuItemCiudad1 = new javax.swing.JMenuItem();
        jMenuItemMarcador1 = new javax.swing.JMenuItem();
        jMenuItemPartidos1 = new javax.swing.JMenuItem();
        jMenuItemEquipos1 = new javax.swing.JMenuItem();
        jMenu_eliminar = new javax.swing.JMenu();
        jMenuItemMarcador2 = new javax.swing.JMenuItem();
        jMenu_modificar = new javax.swing.JMenu();
        jMenuItemMarcador3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/add.png"))); // NOI18N
        jMenuNuevo.setText("Nuevo");

        jMenuItemCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/city.png"))); // NOI18N
        jMenuItemCiudad.setText("Ciudad");
        jMenuItemCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCiudadActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemCiudad);

        jMenuItemEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/team.png"))); // NOI18N
        jMenuItemEquipos.setText("Equipos");
        jMenuItemEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquiposActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemEquipos);

        jMenuItemPartidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/match.png"))); // NOI18N
        jMenuItemPartidos.setText("Partidos");
        jMenuItemPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPartidosActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemPartidos);

        jMenuItemMarcador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/numeric.png"))); // NOI18N
        jMenuItemMarcador.setText("Marcador");
        jMenuItemMarcador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcadorActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemMarcador);

        jMenuArchivo.add(jMenuNuevo);

        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit.png"))); // NOI18N
        jMenuItemSalir.setText("Salir");
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenu_ver.setText("Ver");

        jMenuItemTablaPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bar2.png"))); // NOI18N
        jMenuItemTablaPos.setText("Tabla de Posiciones");
        jMenuItemTablaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaPosActionPerformed(evt);
            }
        });
        jMenu_ver.add(jMenuItemTablaPos);

        jMenuItemCiudad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/city.png"))); // NOI18N
        jMenuItemCiudad1.setText("Ciudad");
        jMenuItemCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCiudad1ActionPerformed(evt);
            }
        });
        jMenu_ver.add(jMenuItemCiudad1);

        jMenuItemMarcador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/numeric.png"))); // NOI18N
        jMenuItemMarcador1.setText("Marcador");
        jMenuItemMarcador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcador1ActionPerformed(evt);
            }
        });
        jMenu_ver.add(jMenuItemMarcador1);

        jMenuItemPartidos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/match.png"))); // NOI18N
        jMenuItemPartidos1.setText("Partidos");
        jMenuItemPartidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPartidos1ActionPerformed(evt);
            }
        });
        jMenu_ver.add(jMenuItemPartidos1);

        jMenuItemEquipos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/team.png"))); // NOI18N
        jMenuItemEquipos1.setText("Equipos");
        jMenuItemEquipos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquipos1ActionPerformed(evt);
            }
        });
        jMenu_ver.add(jMenuItemEquipos1);

        jMenuBar1.add(jMenu_ver);

        jMenu_eliminar.setText("Eliminar");

        jMenuItemMarcador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/numeric.png"))); // NOI18N
        jMenuItemMarcador2.setText("Marcador");
        jMenuItemMarcador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcador2ActionPerformed(evt);
            }
        });
        jMenu_eliminar.add(jMenuItemMarcador2);

        jMenuBar1.add(jMenu_eliminar);

        jMenu_modificar.setText("Modificar");

        jMenuItemMarcador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/numeric.png"))); // NOI18N
        jMenuItemMarcador3.setText("Marcador");
        jMenuItemMarcador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcador3ActionPerformed(evt);
            }
        });
        jMenu_modificar.add(jMenuItemMarcador3);

        jMenuBar1.add(jMenu_modificar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquiposActionPerformed
        equipos e = null;
        try {
            e = new equipos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(e);
        e.show();

    }//GEN-LAST:event_jMenuItemEquiposActionPerformed

    private void jMenuItemCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCiudadActionPerformed
        ciudades e = null;
        e = new ciudades();
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemCiudadActionPerformed

    private void jMenuItemPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPartidosActionPerformed
        partidos e = null;
        try {
            e = new partidos();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(e);
        e.show();
        
    }//GEN-LAST:event_jMenuItemPartidosActionPerformed

    private void jMenuItemMarcadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcadorActionPerformed
        // TODO add your handling code here:
        marcador e = null;
        e = new marcador();
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemMarcadorActionPerformed

    private void jMenuItemTablaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaPosActionPerformed
        // TODO add your handling code here:
        posiciones e = null;
        try {
            e = new posiciones();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemTablaPosActionPerformed

    private void jMenuItemCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCiudad1ActionPerformed
        // TODO add your handling code here:
        ciudades_con e = null;
        try {
            e = new ciudades_con();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemCiudad1ActionPerformed

    private void jMenuItemMarcador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcador1ActionPerformed
        // TODO add your handling code here:
        marcador_con e = null;
        try {
            e = new marcador_con();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemMarcador1ActionPerformed

    private void jMenuItemPartidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPartidos1ActionPerformed
        // TODO add your handling code here:
        partidos_con e = null;
        try {
            e = new partidos_con();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemPartidos1ActionPerformed

    private void jMenuItemEquipos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquipos1ActionPerformed
        // TODO add your handling code here:
        equipos_con e = null;
        try {
            e = new equipos_con();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemEquipos1ActionPerformed

    private void jMenuItemMarcador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcador2ActionPerformed
        // TODO add your handling code here:
        marcador_eli e = null;
        e = new marcador_eli();
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemMarcador2ActionPerformed

    private void jMenuItemMarcador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcador3ActionPerformed
        // TODO add your handling code here:
        marcador_act e = null;
        e = new marcador_act();
        jDesktopPane1.add(e);
        e.show();
    }//GEN-LAST:event_jMenuItemMarcador3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCiudad;
    private javax.swing.JMenuItem jMenuItemCiudad1;
    private javax.swing.JMenuItem jMenuItemEquipos;
    private javax.swing.JMenuItem jMenuItemEquipos1;
    private javax.swing.JMenuItem jMenuItemMarcador;
    private javax.swing.JMenuItem jMenuItemMarcador1;
    private javax.swing.JMenuItem jMenuItemMarcador2;
    private javax.swing.JMenuItem jMenuItemMarcador3;
    private javax.swing.JMenuItem jMenuItemPartidos;
    private javax.swing.JMenuItem jMenuItemPartidos1;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTablaPos;
    private javax.swing.JMenu jMenuNuevo;
    private javax.swing.JMenu jMenu_eliminar;
    private javax.swing.JMenu jMenu_modificar;
    private javax.swing.JMenu jMenu_ver;
    // End of variables declaration//GEN-END:variables
}
