CREATE OR REPLACE TRIGGER ELI_MAR
AFTER DELETE ON MARCADOR
FOR EACH ROW
DECLARE
EQUI_LOC VARCHAR(1);
EQUI_VIS VARCHAR(1);

PAR_JUG_LOC NUMBER;
PAR_JUG_VIS NUMBER;

PAR_GAN_LOC NUMBER;
PAR_GAN_VIS NUMBER;

PAR_EMP_LOC NUMBER;
PAR_EMP_VIS NUMBER;

PAR_PER_LOC NUMBER;
PAR_PER_VIS NUMBER;

GOL_FAV_LOC NUMBER;
GOL_FAV_VIS NUMBER;

GOL_CON_LOC NUMBER;
GOL_CON_VIS NUMBER;

GOL_DIF_LOC NUMBER;
GOL_DIF_VIS NUMBER;

PUNTOS_LOC NUMBER;
PUNTOS_VIS NUMBER;

BEGIN
	SELECT EQUI_LOC_PAR, EQUI_VIS_PAR INTO EQUI_LOC, EQUI_VIS
	FROM PARTIDOS
	WHERE NUM_PAR= :OLD.NUM_PAR_MAR;

	SELECT PAR_JUG_POS, PAR_GAN_POS, PAR_EMP_POS, PAR_PER_POS, GOL_FAV_POS, GOL_CON_POS, GOL_DIF_POS, PUNTOS_POS INTO PAR_JUG_LOC, PAR_GAN_LOC, PAR_EMP_LOC, PAR_PER_LOC, GOL_FAV_LOC, GOL_CON_LOC, GOL_DIF_LOC, PUNTOS_LOC
	FROM POSICIONES
	WHERE EQUIPO_POS=EQUI_LOC;

	SELECT PAR_JUG_POS, PAR_GAN_POS, PAR_EMP_POS, PAR_PER_POS, GOL_FAV_POS, GOL_CON_POS, GOL_DIF_POS, PUNTOS_POS INTO PAR_JUG_VIS, PAR_GAN_VIS, PAR_EMP_VIS, PAR_PER_VIS, GOL_FAV_VIS, GOL_CON_VIS, GOL_DIF_VIS, PUNTOS_VIS
	FROM POSICIONES
	WHERE EQUIPO_POS=EQUI_VIS;

	PAR_JUG_LOC:=PAR_JUG_LOC-1;
	PAR_JUG_VIS:=PAR_JUG_VIS-1;

	UPDATE POSICIONES
	SET PAR_JUG_POS=PAR_JUG_LOC
	WHERE EQUIPO_POS=EQUI_LOC;

	UPDATE POSICIONES
	SET PAR_JUG_POS=PAR_JUG_VIS
	WHERE EQUIPO_POS=EQUI_VIS;
	
	GOL_FAV_LOC:=GOL_FAV_LOC-:OLD.GOL_EQUI_LOC_MAR;
	UPDATE POSICIONES
	SET GOL_FAV_POS=GOL_FAV_LOC
	WHERE EQUIPO_POS=EQUI_LOC;
	
	GOL_CON_LOC:=GOL_CON_LOC-:OLD.GOL_EQUI_VIS_MAR;
	UPDATE POSICIONES
	SET GOL_CON_POS=GOL_CON_LOC
	WHERE EQUIPO_POS=EQUI_LOC;	
	
	GOL_FAV_VIS:=GOL_FAV_VIS-:OLD.GOL_EQUI_VIS_MAR;
	UPDATE POSICIONES
	SET GOL_FAV_POS=GOL_FAV_VIS
	WHERE EQUIPO_POS=EQUI_VIS;
	
	GOL_CON_VIS:=GOL_CON_VIS-:OLD.GOL_EQUI_LOC_MAR;
	UPDATE POSICIONES
	SET GOL_CON_POS=GOL_CON_VIS
	WHERE EQUIPO_POS=EQUI_VIS;	
	
	GOL_DIF_LOC:=GOL_FAV_LOC-GOL_CON_LOC;
	GOL_DIF_VIS:=GOL_FAV_VIS-GOL_CON_VIS;
	
	UPDATE POSICIONES
	SET GOL_DIF_POS=GOL_DIF_LOC
	WHERE EQUIPO_POS=EQUI_LOC;	

	UPDATE POSICIONES
	SET GOL_DIF_POS=GOL_DIF_VIS
	WHERE EQUIPO_POS=EQUI_VIS;	
	
IF :OLD.GOL_EQUI_LOC_MAR > :OLD.GOL_EQUI_VIS_MAR THEN
		PAR_GAN_LOC:=PAR_GAN_LOC-1;
		UPDATE POSICIONES
		SET PAR_GAN_POS=PAR_GAN_LOC
		WHERE EQUIPO_POS=EQUI_LOC;
		
		PAR_PER_VIS:=PAR_PER_VIS-1;
		UPDATE POSICIONES
		SET PAR_PER_POS=PAR_PER_VIS
		WHERE EQUIPO_POS=EQUI_VIS;
		
		PUNTOS_LOC:=PUNTOS_LOC-3;
		UPDATE POSICIONES
		SET PUNTOS_POS=PUNTOS_LOC
		WHERE EQUIPO_POS=EQUI_LOC;
	ELSE
		IF :OLD.GOL_EQUI_LOC_MAR = :OLD.GOL_EQUI_VIS_MAR THEN
			PAR_EMP_LOC:=PAR_EMP_LOC-1;
			UPDATE POSICIONES
			SET PAR_EMP_POS=PAR_EMP_LOC
			WHERE EQUIPO_POS=EQUI_LOC;
			
			PUNTOS_LOC:=PUNTOS_LOC-1;
			UPDATE POSICIONES
			SET PUNTOS_POS=PUNTOS_LOC
			WHERE EQUIPO_POS=EQUI_LOC;
			
			PUNTOS_VIS:=PUNTOS_VIS-1;
			UPDATE POSICIONES
			SET PUNTOS_POS=PUNTOS_VIS
			WHERE EQUIPO_POS=EQUI_VIS;
			
			PAR_EMP_VIS:=PAR_EMP_VIS-1;
			UPDATE POSICIONES
			SET PAR_EMP_POS=PAR_EMP_VIS
			WHERE EQUIPO_POS=EQUI_VIS;
		ELSE
			PAR_GAN_VIS:=PAR_GAN_VIS-1;
			UPDATE POSICIONES
			SET PAR_GAN_POS=PAR_GAN_VIS
			WHERE EQUIPO_POS=EQUI_VIS;
			
			PUNTOS_VIS:=PUNTOS_VIS-3;
			UPDATE POSICIONES
			SET PUNTOS_POS=PUNTOS_VIS
			WHERE EQUIPO_POS=EQUI_VIS;
			
			PAR_PER_LOC:=PAR_PER_LOC-1;
			UPDATE POSICIONES
			SET PAR_PER_POS=PAR_PER_LOC
			WHERE EQUIPO_POS=EQUI_LOC;
		END IF;
END IF;
END;
.
/

DELETE FROM MARCADOR
WHERE NUM_PAR_MAR=3;

DELETE FROM POSICIONES;
DROP TRIGGER ELI_MAR;
DELETE FROM MARCADOR;

DELETE FROM MARCADOR WHERE NUM_PAR_MAR=1;

UPDATE MARCADOR SET GOL_EQUI_LOC_MAR=12, GOL_EQUI_VIS_MAR=23 WHERE NUM_PAR_MAR=2

SELECT * FROM MARCADOR;