
***************************DEBER FINAL******************************************

SE DESEA CREAR UNA BASE DE DATOS PARA CONTROLAR LA TABLA DE POSICIONES DE UN CAMPEONATO, LA TABLA DE GOLEADORES, LA TABLA DE EXPULSADOS Y LA TABLA DE CAMBIOS.

********************************************************************************

EQUIPOS=(COD_EQU, NOM_EQU, DESC_EQU,CIU_EQU)
PARTIDOS=(NUM_PAR, FEC_PAR, ESTADIO)

CONNECT ADMIN
CREATE USER CAMPEONATO IDENTIFIED BY CAMPEONATO;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO CAMPEONATO;

DISCONNECT;
CONNECT CAMPEONATO;
----------------------------------------------------------------------------

CREATE TABLE CIUDADES(
COD_CIU VARCHAR(3) PRIMARY KEY,
NOM_CIU VARCHAR(25) NOT NULL
);

CREATE TABLE EQUIPOS(
    COD_EQU VARCHAR(1) PRIMARY KEY,
    NOM_EQU VARCHAR(15),
    DESC_EQU VARCHAR(15),
    CIU_EQU VARCHAR(12)
);

INSERT INTO EQUIPOS
VALUES('A','AUCAS','ORIENTAL','QUITO');
INSERT INTO EQUIPOS
VALUES('B','BARCELONA','COPIA','GUAYAQUIL');
INSERT INTO EQUIPOS
VALUES('E','EMELEC','BICAMPEON','GUAYAQUIL');
INSERT INTO EQUIPOS
VALUES('L','LIGA','REY','QUITO');
INSERT INTO EQUIPOS
VALUES('M','MACARA','CASIGANA','AMBATO');
INSERT INTO EQUIPOS
VALUES('N','NACIONAL','BITRI','QUITO');

CREATE TABLE PARTIDOS(
    NUM_PAR NUMBER PRIMARY KEY,
    FEC_PAR DATE,
    ESTADIO_PAR VARCHAR(12),
    EQUI_LOC_PAR VARCHAR(1) NOT NULL REFERENCES EQUIPOS(COD_EQU),
    EQUI_VIS_PAR VARCHAR(1) NOT NULL REFERENCES EQUIPOS(COD_EQU)
);

CREATE SEQUENCE NUMERO_PARTIDO
    INCREMENT BY 1
    MAXVALUE 500
    START WITH 1;

INSERT INTO PARTIDOS
VALUES(NUMERO_PARTIDO.NEXTVAL,SYSDATE+6,'BELLAVISTA','M','B');
INSERT INTO PARTIDOS
VALUES(NUMERO_PARTIDO.NEXTVAL,SYSDATE+6,'CAPWELL','E','N');
INSERT INTO PARTIDOS
VALUES(NUMERO_PARTIDO.NEXTVAL,SYSDATE+6,'ATAHUALPA','N','M');
INSERT INTO PARTIDOS
VALUES(NUMERO_PARTIDO.NEXTVAL,SYSDATE+6,'ATAHUALPA','M','E');
INSERT INTO PARTIDOS
VALUES(NUMERO_PARTIDO.NEXTVAL,SYSDATE+6,'ATAHUALPA','L','B');
INSERT INTO PARTIDOS
VALUES(NUMERO_PARTIDO.NEXTVAL,SYSDATE+6,'ATAHUALPA','A','M');

CREATE TABLE MARCADOR(
    GOL_EQUI_LOC_MAR NUMBER,
    GOL_EQUI_VIS_MAR NUMBER,
    NUM_PAR_MAR NUMBER UNIQUE REFERENCES PARTIDOS(NUM_PAR)
);

------------------------------------------------------------------------------
CREATE TABLE POSICIONES(
    EQUIPO_POS VARCHAR(1) UNIQUE REFERENCES EQUIPOS(COD_EQU),
    PAR_JUG_POS NUMBER NOT NULL,
    PAR_GAN_POS NUMBER NOT NULL,
    PAR_EMP_POS NUMBER NOT NULL,
    PAR_PER_POS NUMBER NOT NULL,
    GOL_FAV_POS NUMBER NOT NULL,
    GOL_CON_POS NUMBER NOT NULL,
    GOL_DIF_POS NUMBER NOT NULL,
    PUNTOS_POS NUMBER NOT NULL
);

---------------------------------------------------------------

INSERT INTO POSICIONES
VALUES('A',0,0,0,0,0,0,0,0);
INSERT INTO POSICIONES
VALUES('B',0,0,0,0,0,0,0,0);
INSERT INTO POSICIONES
VALUES('E',0,0,0,0,0,0,0,0);
INSERT INTO POSICIONES
VALUES('L',0,0,0,0,0,0,0,0);
INSERT INTO POSICIONES
VALUES('M',0,0,0,0,0,0,0,0);
INSERT INTO POSICIONES
VALUES('N',0,0,0,0,0,0,0,0);

--------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER CAM_POS_TRG
    AFTER INSERT ON MARCADOR
    FOR EACH ROW
DECLARE
    LOCAL EQUIPOS.COD_EQU%TYPE;
    VISITANTE EQUIPOS.COD_EQU%TYPE;
    PARJUGEQUILOC POSICIONES.PAR_JUG_POS%TYPE;
    PARJUGEQUIVIS POSICIONES.PAR_JUG_POS%TYPE;
    GOLFAVEQUILOC POSICIONES.GOL_FAV_POS%TYPE;
    GOLFAVEQUIVIS POSICIONES.GOL_FAV_POS%TYPE;
    GOLCONEQUILOC POSICIONES.GOL_CON_POS%TYPE;
    GOLCONEQUIVIS POSICIONES.GOL_CON_POS%TYPE;
    GOLDIFEQUILOC POSICIONES.GOL_DIF_POS%TYPE;
    GOLDIFEQUIVIS POSICIONES.GOL_DIF_POS%TYPE;
    PARTGANLOC POSICIONES.PAR_GAN_POS%TYPE;
    PARTGANVIS POSICIONES.PAR_GAN_POS%TYPE;
    PARTPERLOC POSICIONES.PAR_PER_POS%TYPE;
    PARTPERVIS POSICIONES.PAR_PER_POS%TYPE;
    PARTEMPLOC POSICIONES.PAR_EMP_POS%TYPE;
    PARTEMPVIS POSICIONES.PAR_EMP_POS%TYPE;
    PUNTGAN POSICIONES.PUNTOS_POS%TYPE;
    PUNTPER POSICIONES.PUNTOS_POS%TYPE;
    PUNTEMPLOC POSICIONES.PUNTOS_POS%TYPE;
    PUNTEMPVIS POSICIONES.PUNTOS_POS%TYPE;
BEGIN
    SELECT EQUI_LOC_PAR INTO LOCAL
    FROM PARTIDOS
    WHERE NUM_PAR = :NEW.NUM_PAR_MAR;

    SELECT EQUI_VIS_PAR INTO VISITANTE
    FROM PARTIDOS
    WHERE NUM_PAR = :NEW.NUM_PAR_MAR;

    SELECT PAR_JUG_POS INTO PARJUGEQUILOC
    FROM POSICIONES
    WHERE EQUIPO_POS = LOCAL;

    SELECT PAR_JUG_POS INTO PARJUGEQUIVIS
    FROM POSICIONES
    WHERE EQUIPO_POS = VISITANTE;

    SELECT GOL_FAV_POS INTO GOLFAVEQUILOC
    FROM POSICIONES
    WHERE EQUIPO_POS = LOCAL;

    SELECT GOL_FAV_POS INTO GOLFAVEQUIVIS
    FROM POSICIONES
    WHERE EQUIPO_POS = VISITANTE;

    SELECT GOL_CON_POS INTO GOLCONEQUILOC
    FROM POSICIONES
    WHERE EQUIPO_POS = LOCAL;

    SELECT GOL_CON_POS INTO GOLCONEQUIVIS
    FROM POSICIONES
    WHERE EQUIPO_POS = VISITANTE;

    UPDATE POSICIONES
        SET PAR_JUG_POS = PARJUGEQUILOC + 1,
            GOL_FAV_POS = GOLFAVEQUILOC + :NEW.GOL_EQUI_LOC_MAR,
            GOL_CON_POS = GOLCONEQUILOC + :NEW.GOL_EQUI_VIS_MAR,
            GOL_DIF_POS = GOL_FAV_POS - GOL_CON_POS
        WHERE EQUIPO_POS = LOCAL;

    UPDATE POSICIONES
        SET PAR_JUG_POS = PARJUGEQUIVIS + 1,
            GOL_FAV_POS = GOLFAVEQUIVIS + :NEW.GOL_EQUI_VIS_MAR,
            GOL_CON_POS = GOLCONEQUIVIS + :NEW.GOL_EQUI_LOC_MAR,
            GOL_DIF_POS = GOL_FAV_POS - GOL_CON_POS
        WHERE EQUIPO_POS = VISITANTE;

    UPDATE POSICIONES
        SET GOL_DIF_POS = GOL_FAV_POS - GOL_CON_POS
        WHERE EQUIPO_POS = LOCAL;

    UPDATE POSICIONES
        SET GOL_DIF_POS = GOL_FAV_POS - GOL_CON_POS
        WHERE EQUIPO_POS = VISITANTE;

    SELECT PAR_GAN_POS INTO PARTGANLOC
    FROM POSICIONES
    WHERE EQUIPO_POS = LOCAL;

    SELECT PAR_GAN_POS INTO PARTGANVIS
    FROM POSICIONES
    WHERE EQUIPO_POS = VISITANTE;

    SELECT PAR_PER_POS INTO PARTPERLOC
    FROM POSICIONES
    WHERE EQUIPO_POS = LOCAL;

    SELECT PAR_PER_POS INTO PARTPERVIS
    FROM POSICIONES
    WHERE EQUIPO_POS = VISITANTE;

    IF (:NEW.GOL_EQUI_LOC_MAR > :NEW.GOL_EQUI_VIS_MAR) THEN
        UPDATE POSICIONES
            SET PAR_GAN_POS = PARTGANLOC + 1
            WHERE EQUIPO_POS = LOCAL;
        UPDATE POSICIONES
            SET PAR_PER_POS = PARTPERVIS + 1
            WHERE EQUIPO_POS = VISITANTE;
        SELECT PUNTOS_POS INTO PUNTGAN
        FROM POSICIONES
        WHERE EQUIPO_POS = LOCAL;
        UPDATE POSICIONES
            SET PUNTOS_POS = PUNTGAN + 3
            WHERE EQUIPO_POS = LOCAL;
    END IF;

    IF (:NEW.GOL_EQUI_VIS_MAR > :NEW.GOL_EQUI_LOC_MAR) THEN
        UPDATE POSICIONES
            SET PAR_GAN_POS = PARTGANVIS + 1
            WHERE EQUIPO_POS = VISITANTE;
        UPDATE POSICIONES
            SET PAR_PER_POS = PARTPERLOC + 1
            WHERE EQUIPO_POS = LOCAL;
        SELECT PUNTOS_POS INTO PUNTGAN
        FROM POSICIONES
        WHERE EQUIPO_POS = VISITANTE;
        UPDATE POSICIONES
            SET PUNTOS_POS = PUNTGAN + 3
            WHERE EQUIPO_POS = VISITANTE;
    END IF;

    IF (:NEW.GOL_EQUI_LOC_MAR = :NEW.GOL_EQUI_VIS_MAR) THEN
        SELECT PAR_EMP_POS INTO PARTEMPLOC
        FROM POSICIONES
        WHERE EQUIPO_POS = LOCAL;
        SELECT PAR_EMP_POS INTO PARTEMPVIS
        FROM POSICIONES
        WHERE EQUIPO_POS = VISITANTE;
        UPDATE POSICIONES
            SET PAR_EMP_POS = PARTEMPLOC + 1
            WHERE EQUIPO_POS = LOCAL;
        UPDATE POSICIONES
            SET PAR_EMP_POS = PARTEMPVIS + 1
            WHERE EQUIPO_POS = VISITANTE;

        SELECT PUNTOS_POS INTO PUNTEMPLOC
        FROM POSICIONES
        WHERE EQUIPO_POS = LOCAL;
        SELECT PUNTOS_POS INTO PUNTEMPVIS
        FROM POSICIONES
        WHERE EQUIPO_POS = VISITANTE;
        UPDATE POSICIONES
            SET PUNTOS_POS = PUNTEMPLOC + 1
            WHERE EQUIPO_POS = LOCAL;
        UPDATE POSICIONES
            SET PUNTOS_POS = PUNTEMPVIS + 1
            WHERE EQUIPO_POS = VISITANTE;
    END IF;

END CAM_POS_TRG;
.
/

------------------------------------------------------------------
INSERT INTO MARCADOR
    VALUES(3,3,1);

INSERT INTO MARCADOR
    VALUES(6,1,2);

INSERT INTO MARCADOR
    VALUES(3,3,3);

INSERT INTO MARCADOR
    VALUES(2,2,4);

----------------------------------------------------------------

SELECT * FROM POSICIONES;

------------------------------------------------------------------
SELECT P.EQUIPO_POS, E.NOM_EQU, P.PAR_JUG_POS, P.PAR_GAN_POS, P.PAR_PER_POS, P.PAR_EMP_POS, P.PUNTOS_POS, P.GOL_FAV_POS, P.GOL_CON_POS, P.GOL_DIF_POS, P.PUNTOS_POS
FROM POSICIONES P,EQUIPOS E
WHERE P.EQUIPO_POS=E.COD_EQU;

SELECT E.NOM_EQU,P.PUNTOS, P.GD
FROM POSICIONES P,EQUIPOS E
WHERE P.EQUIPO=E.COD_EQU
ORDER BY P.PUNTOS DESC, P.GD DESC;

--------------------------------------------------------------------------
DEBER: TERMINAR COMPLETAMENTE EL SISTEMA Y ENLAZARLO A UNA INTERFAZ.
GRUP�S DE 2 PERSONAS PARA EL DIA LUNES ( EXPOSICION)

MENU:

1) INTERFAZ PARA PLANIFICAR UN PARTIDO.

NUM_PAR:
EQUL  N
EQUV  M
FECHA:
ESTADIO:

	GRABAR
INSERT INTO PARTIDOS(NUM_PAR,EQUIL,...)
VALUES(SEQ.NEXTVAL,...);

MARCADOR:

----------------------------------------------------------------------------
2) REGISTRAR EL MARCADOR DEL PARTIDO.
3) CONSULTAR LA TABLA DE POSICIONES COMPLETA.
-----------------------------------------------------------------------------
*****************************************************************************
PROYECTO FINAL
****************************************************************************
COMPLEMENTAR LA BASE DE CAMPEONATO A�ADIENDO JUGADORES A CADA EQUIPO, DE MANERA QUE NO SE REGISTRE EL MARCADOR DIRECTAMENTE POR LOS GOLES DEL EQUIPO, SINO POR LOS GOLES QUE HAGAN LOS JUGADORES.
TENIENDO EN CUENTA SI EL JUGADOR ESTUVO PRESENTE O NO EN LA CANCHA O FUE SUSTITUIDO.(TENER EN CUENTA LOS MINUTOS)
SE DEBE LLEVAR UN CONTROLDEL GOLEADOR DEL CAMPEONATO.
SE DEBE TENER EN CUENTA LAS AMONESTACIONES(AMARILLA) O (ROJA).



TRIGGERS PARA 
-CUANDO SE ACTUALIZA UN MARCADOR SE ALTERA LA TABLA DE POSICIONES 
(SE PUEDE ACTIALIZAR UNO O LOS 2 GOLES)

-CUANDO SE ELIMINA UN MARCADOR CAMBIA LA TABLA DE POSICIONES


